import XCTest
@testable import CommandLine

class CountryCodeSpec: XCTestCase {
    func testRawValues() {
        XCTAssertEqual(CountryCode.afghanistan.rawValue, "AF")
        XCTAssertEqual(CountryCode.alandIslands.rawValue, "AX")
        XCTAssertEqual(CountryCode.albania.rawValue, "AL")
        XCTAssertEqual(CountryCode.algeria.rawValue, "DZ")
        XCTAssertEqual(CountryCode.americanSamoa.rawValue, "AS")
        XCTAssertEqual(CountryCode.andorra.rawValue, "AD")
        XCTAssertEqual(CountryCode.angola.rawValue, "AO")
        XCTAssertEqual(CountryCode.anguilla.rawValue, "AI")
        XCTAssertEqual(CountryCode.antarctica.rawValue, "AQ")
        XCTAssertEqual(CountryCode.antiguaAndBarbuda.rawValue, "AG")
        XCTAssertEqual(CountryCode.argentina.rawValue, "AR")
        XCTAssertEqual(CountryCode.armenia.rawValue, "AM")
        XCTAssertEqual(CountryCode.aruba.rawValue, "AW")
        XCTAssertEqual(CountryCode.australia.rawValue, "AU")
        XCTAssertEqual(CountryCode.austria.rawValue, "AT")
        XCTAssertEqual(CountryCode.azerbaijan.rawValue, "AZ")
        XCTAssertEqual(CountryCode.bahamas.rawValue, "BS")
        XCTAssertEqual(CountryCode.bahrain.rawValue, "BH")
        XCTAssertEqual(CountryCode.bangladesh.rawValue, "BD")
        XCTAssertEqual(CountryCode.barbados.rawValue, "BB")
        XCTAssertEqual(CountryCode.belarus.rawValue, "BY")
        XCTAssertEqual(CountryCode.belgium.rawValue, "BE")
        XCTAssertEqual(CountryCode.belize.rawValue, "BZ")
        XCTAssertEqual(CountryCode.benin.rawValue, "BJ")
        XCTAssertEqual(CountryCode.bermuda.rawValue, "BM")
        XCTAssertEqual(CountryCode.bhutan.rawValue, "BT")
        XCTAssertEqual(CountryCode.bolivia.rawValue, "BO")
        XCTAssertEqual(CountryCode.bonaire.rawValue, "BQ")
        XCTAssertEqual(CountryCode.bosniaAndHerzegovina.rawValue, "BA")
        XCTAssertEqual(CountryCode.botswana.rawValue, "BW")
        XCTAssertEqual(CountryCode.bouvetIsland.rawValue, "BV")
        XCTAssertEqual(CountryCode.brazil.rawValue, "BR")
        XCTAssertEqual(CountryCode.britishIndianOceanTerritory.rawValue, "IO")
        XCTAssertEqual(CountryCode.bruneiDarussalam.rawValue, "BN")
        XCTAssertEqual(CountryCode.bulgaria.rawValue, "BG")
        XCTAssertEqual(CountryCode.burkinaFaso.rawValue, "BF")
        XCTAssertEqual(CountryCode.burundi.rawValue, "BI")
        XCTAssertEqual(CountryCode.cambodia.rawValue, "KH")
        XCTAssertEqual(CountryCode.cameroon.rawValue, "CM")
        XCTAssertEqual(CountryCode.canada.rawValue, "CA")
        XCTAssertEqual(CountryCode.capeVerde.rawValue, "CV")
        XCTAssertEqual(CountryCode.caymanIslands.rawValue, "KY")
        XCTAssertEqual(CountryCode.centralAfricanRepublic.rawValue, "CF")
        XCTAssertEqual(CountryCode.chad.rawValue, "TD")
        XCTAssertEqual(CountryCode.chile.rawValue, "CL")
        XCTAssertEqual(CountryCode.china.rawValue, "CN")
        XCTAssertEqual(CountryCode.christmasIsland.rawValue, "CX")
        XCTAssertEqual(CountryCode.cocosKeelingIslands.rawValue, "CC")
        XCTAssertEqual(CountryCode.colombia.rawValue, "CO")
        XCTAssertEqual(CountryCode.comoros.rawValue, "KM")
        XCTAssertEqual(CountryCode.congo.rawValue, "CG")
        XCTAssertEqual(CountryCode.congoTheDemocraticRepublicOfThe.rawValue, "CD")
        XCTAssertEqual(CountryCode.cookIslands.rawValue, "CK")
        XCTAssertEqual(CountryCode.costaRica.rawValue, "CR")
        XCTAssertEqual(CountryCode.coteDIvoire.rawValue, "CI")
        XCTAssertEqual(CountryCode.croatia.rawValue, "HR")
        XCTAssertEqual(CountryCode.cuba.rawValue, "CU")
        XCTAssertEqual(CountryCode.curacao.rawValue, "CW")
        XCTAssertEqual(CountryCode.cyprus.rawValue, "CY")
        XCTAssertEqual(CountryCode.czechRepublic.rawValue, "CZ")
        XCTAssertEqual(CountryCode.denmark.rawValue, "DK")
        XCTAssertEqual(CountryCode.djibouti.rawValue, "DJ")
        XCTAssertEqual(CountryCode.dominica.rawValue, "DM")
        XCTAssertEqual(CountryCode.dominicanRepublic.rawValue, "DO")
        XCTAssertEqual(CountryCode.ecuador.rawValue, "EC")
        XCTAssertEqual(CountryCode.egypt.rawValue, "EG")
        XCTAssertEqual(CountryCode.elSalvador.rawValue, "SV")
        XCTAssertEqual(CountryCode.equatorialGuinea.rawValue, "GQ")
        XCTAssertEqual(CountryCode.eritrea.rawValue, "ER")
        XCTAssertEqual(CountryCode.estonia.rawValue, "EE")
        XCTAssertEqual(CountryCode.ethiopia.rawValue, "ET")
        XCTAssertEqual(CountryCode.falklandIslandsMalvinas.rawValue, "FK")
        XCTAssertEqual(CountryCode.faroeIslands.rawValue, "FO")
        XCTAssertEqual(CountryCode.fiji.rawValue, "FJ")
        XCTAssertEqual(CountryCode.finland.rawValue, "FI")
        XCTAssertEqual(CountryCode.france.rawValue, "FR")
        XCTAssertEqual(CountryCode.frenchGuiana.rawValue, "GF")
        XCTAssertEqual(CountryCode.frenchPolynesia.rawValue, "PF")
        XCTAssertEqual(CountryCode.frenchSouthernTerritories.rawValue, "TF")
        XCTAssertEqual(CountryCode.gabon.rawValue, "GA")
        XCTAssertEqual(CountryCode.gambia.rawValue, "GM")
        XCTAssertEqual(CountryCode.georgia.rawValue, "GE")
        XCTAssertEqual(CountryCode.germany.rawValue, "DE")
        XCTAssertEqual(CountryCode.ghana.rawValue, "GH")
        XCTAssertEqual(CountryCode.gibraltar.rawValue, "GI")
        XCTAssertEqual(CountryCode.greece.rawValue, "GR")
        XCTAssertEqual(CountryCode.greenland.rawValue, "GL")
        XCTAssertEqual(CountryCode.grenada.rawValue, "GD")
        XCTAssertEqual(CountryCode.guadeloupe.rawValue, "GP")
        XCTAssertEqual(CountryCode.guam.rawValue, "GU")
        XCTAssertEqual(CountryCode.guatemala.rawValue, "GT")
        XCTAssertEqual(CountryCode.guernsey.rawValue, "GG")
        XCTAssertEqual(CountryCode.guinea.rawValue, "GN")
        XCTAssertEqual(CountryCode.guineaBissau.rawValue, "GW")
        XCTAssertEqual(CountryCode.guyana.rawValue, "GY")
        XCTAssertEqual(CountryCode.haiti.rawValue, "HT")
        XCTAssertEqual(CountryCode.heardIslandAndMcdonaldIslands.rawValue, "HM")
        XCTAssertEqual(CountryCode.holySeeVaticanCityState.rawValue, "VA")
        XCTAssertEqual(CountryCode.honduras.rawValue, "HN")
        XCTAssertEqual(CountryCode.hongKong.rawValue, "HK")
        XCTAssertEqual(CountryCode.hungary.rawValue, "HU")
        XCTAssertEqual(CountryCode.iceland.rawValue, "IS")
        XCTAssertEqual(CountryCode.india.rawValue, "IN")
        XCTAssertEqual(CountryCode.indonesia.rawValue, "ID")
        XCTAssertEqual(CountryCode.iranIslamicRepublicOf.rawValue, "IR")
        XCTAssertEqual(CountryCode.iraq.rawValue, "IQ")
        XCTAssertEqual(CountryCode.ireland.rawValue, "IE")
        XCTAssertEqual(CountryCode.isleOfMan.rawValue, "IM")
        XCTAssertEqual(CountryCode.israel.rawValue, "IL")
        XCTAssertEqual(CountryCode.italy.rawValue, "IT")
        XCTAssertEqual(CountryCode.jamaica.rawValue, "JM")
        XCTAssertEqual(CountryCode.japan.rawValue, "JP")
        XCTAssertEqual(CountryCode.jersey.rawValue, "JE")
        XCTAssertEqual(CountryCode.jordan.rawValue, "JO")
        XCTAssertEqual(CountryCode.kazakhstan.rawValue, "KZ")
        XCTAssertEqual(CountryCode.kenya.rawValue, "KE")
        XCTAssertEqual(CountryCode.kiribati.rawValue, "KI")
        XCTAssertEqual(CountryCode.koreaDemocraticPeopleSRepublicOf.rawValue, "KP")
        XCTAssertEqual(CountryCode.koreaRepublicOf.rawValue, "KR")
        XCTAssertEqual(CountryCode.kuwait.rawValue, "KW")
        XCTAssertEqual(CountryCode.kyrgyzstan.rawValue, "KG")
        XCTAssertEqual(CountryCode.laoPeopleSDemocraticRepublic.rawValue, "LA")
        XCTAssertEqual(CountryCode.latvia.rawValue, "LV")
        XCTAssertEqual(CountryCode.lebanon.rawValue, "LB")
        XCTAssertEqual(CountryCode.lesotho.rawValue, "LS")
        XCTAssertEqual(CountryCode.liberia.rawValue, "LR")
        XCTAssertEqual(CountryCode.libyanArabJamahiriya.rawValue, "LY")
        XCTAssertEqual(CountryCode.liechtenstein.rawValue, "LI")
        XCTAssertEqual(CountryCode.lithuania.rawValue, "LT")
        XCTAssertEqual(CountryCode.luxembourg.rawValue, "LU")
        XCTAssertEqual(CountryCode.macao.rawValue, "MO")
        XCTAssertEqual(CountryCode.macedoniaTheFormerYugoslavRepublicOf.rawValue, "MK")
        XCTAssertEqual(CountryCode.madagascar.rawValue, "MG")
        XCTAssertEqual(CountryCode.malawi.rawValue, "MW")
        XCTAssertEqual(CountryCode.malaysia.rawValue, "MY")
        XCTAssertEqual(CountryCode.maldives.rawValue, "MV")
        XCTAssertEqual(CountryCode.mali.rawValue, "ML")
        XCTAssertEqual(CountryCode.malta.rawValue, "MT")
        XCTAssertEqual(CountryCode.marshallIslands.rawValue, "MH")
        XCTAssertEqual(CountryCode.martinique.rawValue, "MQ")
        XCTAssertEqual(CountryCode.mauritania.rawValue, "MR")
        XCTAssertEqual(CountryCode.mauritius.rawValue, "MU")
        XCTAssertEqual(CountryCode.mayotte.rawValue, "YT")
        XCTAssertEqual(CountryCode.mexico.rawValue, "MX")
        XCTAssertEqual(CountryCode.micronesiaFederatedStatesOf.rawValue, "FM")
        XCTAssertEqual(CountryCode.moldova.rawValue, "MD")
        XCTAssertEqual(CountryCode.monaco.rawValue, "MC")
        XCTAssertEqual(CountryCode.mongolia.rawValue, "MN")
        XCTAssertEqual(CountryCode.montenegro.rawValue, "ME")
        XCTAssertEqual(CountryCode.montserrat.rawValue, "MS")
        XCTAssertEqual(CountryCode.morocco.rawValue, "MA")
        XCTAssertEqual(CountryCode.mozambique.rawValue, "MZ")
        XCTAssertEqual(CountryCode.myanmar.rawValue, "MM")
        XCTAssertEqual(CountryCode.namibia.rawValue, "NA")
        XCTAssertEqual(CountryCode.nauru.rawValue, "NR")
        XCTAssertEqual(CountryCode.nepal.rawValue, "NP")
        XCTAssertEqual(CountryCode.netherlands.rawValue, "NL")
        XCTAssertEqual(CountryCode.newCaledonia.rawValue, "NC")
        XCTAssertEqual(CountryCode.newZealand.rawValue, "NZ")
        XCTAssertEqual(CountryCode.nicaragua.rawValue, "NI")
        XCTAssertEqual(CountryCode.niger.rawValue, "NE")
        XCTAssertEqual(CountryCode.nigeria.rawValue, "NG")
        XCTAssertEqual(CountryCode.niue.rawValue, "NU")
        XCTAssertEqual(CountryCode.norfolkIsland.rawValue, "NF")
        XCTAssertEqual(CountryCode.northernMarianaIslands.rawValue, "MP")
        XCTAssertEqual(CountryCode.norway.rawValue, "NO")
        XCTAssertEqual(CountryCode.oman.rawValue, "OM")
        XCTAssertEqual(CountryCode.pakistan.rawValue, "PK")
        XCTAssertEqual(CountryCode.palau.rawValue, "PW")
        XCTAssertEqual(CountryCode.palestinianTerritoryOccupied.rawValue, "PS")
        XCTAssertEqual(CountryCode.panama.rawValue, "PA")
        XCTAssertEqual(CountryCode.papuaNewGuinea.rawValue, "PG")
        XCTAssertEqual(CountryCode.paraguay.rawValue, "PY")
        XCTAssertEqual(CountryCode.peru.rawValue, "PE")
        XCTAssertEqual(CountryCode.philippines.rawValue, "PH")
        XCTAssertEqual(CountryCode.pitcairn.rawValue, "PN")
        XCTAssertEqual(CountryCode.poland.rawValue, "PL")
        XCTAssertEqual(CountryCode.portugal.rawValue, "PT")
        XCTAssertEqual(CountryCode.puertoRico.rawValue, "PR")
        XCTAssertEqual(CountryCode.qata.rawValue, "QA")
        XCTAssertEqual(CountryCode.reunion.rawValue, "RE")
        XCTAssertEqual(CountryCode.romania.rawValue, "RO")
        XCTAssertEqual(CountryCode.russianFederation.rawValue, "RU")
        XCTAssertEqual(CountryCode.rwanda.rawValue, "RW")
        XCTAssertEqual(CountryCode.saintBartholemy.rawValue, "BL")
        XCTAssertEqual(CountryCode.saintHelena.rawValue, "SH")
        XCTAssertEqual(CountryCode.saintKittsAndNevis.rawValue, "KN")
        XCTAssertEqual(CountryCode.saintLucia.rawValue, "LC")
        XCTAssertEqual(CountryCode.saintMartin.rawValue, "MF")
        XCTAssertEqual(CountryCode.saintPierreAndMiquelon.rawValue, "PM")
        XCTAssertEqual(CountryCode.saintVincentAndTheGrenadines.rawValue, "VC")
        XCTAssertEqual(CountryCode.samoa.rawValue, "WS")
        XCTAssertEqual(CountryCode.sanMarino.rawValue, "SM")
        XCTAssertEqual(CountryCode.saoTomeAndPrincipe.rawValue, "ST")
        XCTAssertEqual(CountryCode.saudiArabia.rawValue, "SA")
        XCTAssertEqual(CountryCode.senegal.rawValue, "SN")
        XCTAssertEqual(CountryCode.serbia.rawValue, "RS")
        XCTAssertEqual(CountryCode.seychelles.rawValue, "SC")
        XCTAssertEqual(CountryCode.sierraLeone.rawValue, "SL")
        XCTAssertEqual(CountryCode.sintMaarten.rawValue, "SX")
        XCTAssertEqual(CountryCode.singapore.rawValue, "SG")
        XCTAssertEqual(CountryCode.slovakia.rawValue, "SK")
        XCTAssertEqual(CountryCode.slovenia.rawValue, "SI")
        XCTAssertEqual(CountryCode.solomonIslands.rawValue, "SB")
        XCTAssertEqual(CountryCode.somalia.rawValue, "SO")
        XCTAssertEqual(CountryCode.southAfrica.rawValue, "ZA")
        XCTAssertEqual(CountryCode.southGeorgiaAndTheSouthSandwichIslands.rawValue, "GS")
        XCTAssertEqual(CountryCode.spain.rawValue, "ES")
        XCTAssertEqual(CountryCode.sriLanka.rawValue, "LK")
        XCTAssertEqual(CountryCode.sudan.rawValue, "SD")
        XCTAssertEqual(CountryCode.suriname.rawValue, "SR")
        XCTAssertEqual(CountryCode.svalbardAndJanMayen.rawValue, "SJ")
        XCTAssertEqual(CountryCode.swaziland.rawValue, "SZ")
        XCTAssertEqual(CountryCode.sweden.rawValue, "SE")
        XCTAssertEqual(CountryCode.switzerland.rawValue, "CH")
        XCTAssertEqual(CountryCode.syrianArabRepublic.rawValue, "SY")
        XCTAssertEqual(CountryCode.taiwan.rawValue, "TW")
        XCTAssertEqual(CountryCode.tajikistan.rawValue, "TJ")
        XCTAssertEqual(CountryCode.tanzaniaUnitedRepublicOf.rawValue, "TZ")
        XCTAssertEqual(CountryCode.thailand.rawValue, "TH")
        XCTAssertEqual(CountryCode.timorLeste.rawValue, "TL")
        XCTAssertEqual(CountryCode.togo.rawValue, "TG")
        XCTAssertEqual(CountryCode.tokelau.rawValue, "TK")
        XCTAssertEqual(CountryCode.tonga.rawValue, "TO")
        XCTAssertEqual(CountryCode.trinidadAndTobago.rawValue, "TT")
        XCTAssertEqual(CountryCode.tunisia.rawValue, "TN")
        XCTAssertEqual(CountryCode.turkey.rawValue, "TR")
        XCTAssertEqual(CountryCode.turkmenistan.rawValue, "TM")
        XCTAssertEqual(CountryCode.turksAndCaicosIslands.rawValue, "TC")
        XCTAssertEqual(CountryCode.tuvalu.rawValue, "TV")
        XCTAssertEqual(CountryCode.uganda.rawValue, "UG")
        XCTAssertEqual(CountryCode.ukraine.rawValue, "UA")
        XCTAssertEqual(CountryCode.unitedArabEmirates.rawValue, "AE")
        XCTAssertEqual(CountryCode.unitedKingdom.rawValue, "GB")
        XCTAssertEqual(CountryCode.unitedStates.rawValue, "US")
        XCTAssertEqual(CountryCode.unitedStatesMinorOutlyingIslands.rawValue, "UM")
        XCTAssertEqual(CountryCode.uruguay.rawValue, "UY")
        XCTAssertEqual(CountryCode.uzbekistan.rawValue, "UZ")
        XCTAssertEqual(CountryCode.vanuatu.rawValue, "VU")
        XCTAssertEqual(CountryCode.venezuela.rawValue, "VE")
        XCTAssertEqual(CountryCode.vietNam.rawValue, "VN")
        XCTAssertEqual(CountryCode.virginIslandsBritish.rawValue, "VG")
        XCTAssertEqual(CountryCode.virginIslandsUS.rawValue, "VI")
        XCTAssertEqual(CountryCode.wallisAndFutuna.rawValue, "WF")
        XCTAssertEqual(CountryCode.westernSahara.rawValue, "EH")
        XCTAssertEqual(CountryCode.yemen.rawValue, "YE")
        XCTAssertEqual(CountryCode.zambia.rawValue, "ZM")
        XCTAssertEqual(CountryCode.zimbabwe.rawValue, "ZW")
    }
    
    func testDescriptions() {
        XCTAssertEqual(CountryCode.afghanistan.description, "Afghanistan")
        XCTAssertEqual(CountryCode.alandIslands.description, "AlandIslands")
        XCTAssertEqual(CountryCode.albania.description, "Albania")
        XCTAssertEqual(CountryCode.algeria.description, "Algeria")
        XCTAssertEqual(CountryCode.americanSamoa.description, "AmericanSamoa")
        XCTAssertEqual(CountryCode.andorra.description, "Andorra")
        XCTAssertEqual(CountryCode.angola.description, "Angola")
        XCTAssertEqual(CountryCode.anguilla.description, "Anguilla")
        XCTAssertEqual(CountryCode.antarctica.description, "Antarctica")
        XCTAssertEqual(CountryCode.antiguaAndBarbuda.description, "Antigua An dBarbuda")
        XCTAssertEqual(CountryCode.argentina.description, "Argentina")
        XCTAssertEqual(CountryCode.armenia.description, "Armenia")
        XCTAssertEqual(CountryCode.aruba.description, "Aruba")
        XCTAssertEqual(CountryCode.australia.description, "Australia")
        XCTAssertEqual(CountryCode.austria.description, "Austria")
        XCTAssertEqual(CountryCode.azerbaijan.description, "Azerbaijan")
        XCTAssertEqual(CountryCode.bahamas.description, "Bahamas")
        XCTAssertEqual(CountryCode.bahrain.description, "Bahrain")
        XCTAssertEqual(CountryCode.bangladesh.description, "Bangladesh")
        XCTAssertEqual(CountryCode.barbados.description, "Barbados")
        XCTAssertEqual(CountryCode.belarus.description, "Belarus")
        XCTAssertEqual(CountryCode.belgium.description, "Belgium")
        XCTAssertEqual(CountryCode.belize.description, "Belize")
        XCTAssertEqual(CountryCode.benin.description, "Benin")
        XCTAssertEqual(CountryCode.bermuda.description, "Bermuda")
        XCTAssertEqual(CountryCode.bhutan.description, "Bhutan")
        XCTAssertEqual(CountryCode.bolivia.description, "Bolivia")
        XCTAssertEqual(CountryCode.bonaire.description, "Bonaire")
        XCTAssertEqual(CountryCode.bosniaAndHerzegovina.description, "Bosnia And Herzegovina")
        XCTAssertEqual(CountryCode.botswana.description, "Botswana")
        XCTAssertEqual(CountryCode.bouvetIsland.description, "Bouvet Island")
        XCTAssertEqual(CountryCode.brazil.description, "Brazil")
        XCTAssertEqual(CountryCode.britishIndianOceanTerritory.description, "British Indian Ocean Territory")
        XCTAssertEqual(CountryCode.bruneiDarussalam.description, "Brunei Darussalam")
        XCTAssertEqual(CountryCode.bulgaria.description, "Bulgaria")
        XCTAssertEqual(CountryCode.burkinaFaso.description, "Burkina Faso")
        XCTAssertEqual(CountryCode.burundi.description, "Burundi")
        XCTAssertEqual(CountryCode.cambodia.description, "Cambodia")
        XCTAssertEqual(CountryCode.cameroon.description, "Cameroon")
        XCTAssertEqual(CountryCode.canada.description, "Canada")
        XCTAssertEqual(CountryCode.capeVerde.description, "CapeVerde")
        XCTAssertEqual(CountryCode.caymanIslands.description, "Cayman Islands")
        XCTAssertEqual(CountryCode.centralAfricanRepublic.description, "Central African Republic")
        XCTAssertEqual(CountryCode.chad.description, "Chad")
        XCTAssertEqual(CountryCode.chile.description, "Chile")
        XCTAssertEqual(CountryCode.china.description, "China")
        XCTAssertEqual(CountryCode.christmasIsland.description, "Christmas Island")
        XCTAssertEqual(CountryCode.cocosKeelingIslands.description, "Cocos (Keeling) Islands")
        XCTAssertEqual(CountryCode.colombia.description, "Colombia")
        XCTAssertEqual(CountryCode.comoros.description, "Comoros")
        XCTAssertEqual(CountryCode.congo.description, "Congo")
        XCTAssertEqual(CountryCode.congoTheDemocraticRepublicOfThe.description, "Congo, The Democratic Republic Of The")
        XCTAssertEqual(CountryCode.cookIslands.description, "Cook Islands")
        XCTAssertEqual(CountryCode.costaRica.description, "Costa Rica")
        XCTAssertEqual(CountryCode.coteDIvoire.description, "Cote D'Ivoire")
        XCTAssertEqual(CountryCode.croatia.description, "Croatia")
        XCTAssertEqual(CountryCode.cuba.description, "Cuba")
        XCTAssertEqual(CountryCode.curacao.description, "Curacao")
        XCTAssertEqual(CountryCode.cyprus.description, "Cyprus")
        XCTAssertEqual(CountryCode.czechRepublic.description, "Czech Republic")
        XCTAssertEqual(CountryCode.denmark.description, "Denmark")
        XCTAssertEqual(CountryCode.djibouti.description, "Djibouti")
        XCTAssertEqual(CountryCode.dominica.description, "Dominica")
        XCTAssertEqual(CountryCode.dominicanRepublic.description, "Dominican Republic")
        XCTAssertEqual(CountryCode.ecuador.description, "Ecuador")
        XCTAssertEqual(CountryCode.egypt.description, "Egypt")
        XCTAssertEqual(CountryCode.elSalvador.description, "El Salvador")
        XCTAssertEqual(CountryCode.equatorialGuinea.description, "Equatorial Guinea")
        XCTAssertEqual(CountryCode.eritrea.description, "Eritrea")
        XCTAssertEqual(CountryCode.estonia.description, "Estonia")
        XCTAssertEqual(CountryCode.ethiopia.description, "Ethiopia")
        XCTAssertEqual(CountryCode.falklandIslandsMalvinas.description, "Falkland Islands (Malvinas)")
        XCTAssertEqual(CountryCode.faroeIslands.description, "Faroe Islands")
        XCTAssertEqual(CountryCode.fiji.description, "Fiji")
        XCTAssertEqual(CountryCode.finland.description, "Finland")
        XCTAssertEqual(CountryCode.france.description, "France")
        XCTAssertEqual(CountryCode.frenchGuiana.description, "French Guiana")
        XCTAssertEqual(CountryCode.frenchPolynesia.description, "French Polynesia")
        XCTAssertEqual(CountryCode.frenchSouthernTerritories.description, "French Southern Territories")
        XCTAssertEqual(CountryCode.gabon.description, "Gabon")
        XCTAssertEqual(CountryCode.gambia.description, "Gambia")
        XCTAssertEqual(CountryCode.georgia.description, "Georgia")
        XCTAssertEqual(CountryCode.germany.description, "Germany")
        XCTAssertEqual(CountryCode.ghana.description, "Ghana")
        XCTAssertEqual(CountryCode.gibraltar.description, "Gibraltar")
        XCTAssertEqual(CountryCode.greece.description, "Greece")
        XCTAssertEqual(CountryCode.greenland.description, "Greenland")
        XCTAssertEqual(CountryCode.grenada.description, "Grenada")
        XCTAssertEqual(CountryCode.guadeloupe.description, "Guadeloupe")
        XCTAssertEqual(CountryCode.guam.description, "Guam")
        XCTAssertEqual(CountryCode.guatemala.description, "Guatemala")
        XCTAssertEqual(CountryCode.guernsey.description, "Guernsey")
        XCTAssertEqual(CountryCode.guinea.description, "Guinea")
        XCTAssertEqual(CountryCode.guineaBissau.description, "Guinea-Bissau")
        XCTAssertEqual(CountryCode.guyana.description, "Guyana")
        XCTAssertEqual(CountryCode.haiti.description, "Haiti")
        XCTAssertEqual(CountryCode.heardIslandAndMcdonaldIslands.description, "Heard Island And Mcdonald Islands")
        XCTAssertEqual(CountryCode.holySeeVaticanCityState.description, "Holy See (Vatican City State)")
        XCTAssertEqual(CountryCode.honduras.description, "Honduras")
        XCTAssertEqual(CountryCode.hongKong.description, "Hong Kong")
        XCTAssertEqual(CountryCode.hungary.description, "Hungary")
        XCTAssertEqual(CountryCode.iceland.description, "Iceland")
        XCTAssertEqual(CountryCode.india.description, "India")
        XCTAssertEqual(CountryCode.indonesia.description, "Indonesia")
        XCTAssertEqual(CountryCode.iranIslamicRepublicOf.description, "Iran, Islamic Republic Of")
        XCTAssertEqual(CountryCode.iraq.description, "Iraq")
        XCTAssertEqual(CountryCode.ireland.description, "Ireland")
        XCTAssertEqual(CountryCode.isleOfMan.description, "Isle Of Man")
        XCTAssertEqual(CountryCode.israel.description, "Israel")
        XCTAssertEqual(CountryCode.italy.description, "Italy")
        XCTAssertEqual(CountryCode.jamaica.description, "Jamaica")
        XCTAssertEqual(CountryCode.japan.description, "Japan")
        XCTAssertEqual(CountryCode.jersey.description, "Jersey")
        XCTAssertEqual(CountryCode.jordan.description, "Jordan")
        XCTAssertEqual(CountryCode.kazakhstan.description, "Kazakhstan")
        XCTAssertEqual(CountryCode.kenya.description, "Kenya")
        XCTAssertEqual(CountryCode.kiribati.description, "Kiribati")
        XCTAssertEqual(CountryCode.koreaDemocraticPeopleSRepublicOf.description, "Korea, Democratic People's Republic Of")
        XCTAssertEqual(CountryCode.koreaRepublicOf.description, "Korea, Republic Of")
        XCTAssertEqual(CountryCode.kuwait.description, "Kuwait")
        XCTAssertEqual(CountryCode.kyrgyzstan.description, "Kyrgyzstan")
        XCTAssertEqual(CountryCode.laoPeopleSDemocraticRepublic.description, "Lao People's Democratic Republic")
        XCTAssertEqual(CountryCode.latvia.description, "Latvia")
        XCTAssertEqual(CountryCode.lebanon.description, "Lebanon")
        XCTAssertEqual(CountryCode.lesotho.description, "Lesotho")
        XCTAssertEqual(CountryCode.liberia.description, "Liberia")
        XCTAssertEqual(CountryCode.libyanArabJamahiriya.description, "Libyan Arab Jamahiriya")
        XCTAssertEqual(CountryCode.liechtenstein.description, "Liechtenstein")
        XCTAssertEqual(CountryCode.lithuania.description, "Lithuania")
        XCTAssertEqual(CountryCode.luxembourg.description, "Luxembourg")
        XCTAssertEqual(CountryCode.macao.description, "Macao")
        XCTAssertEqual(CountryCode.macedoniaTheFormerYugoslavRepublicOf.description, "Macedonia, The Former Yugoslav Republic Of")
        XCTAssertEqual(CountryCode.madagascar.description, "Madagascar")
        XCTAssertEqual(CountryCode.malawi.description, "Malawi")
        XCTAssertEqual(CountryCode.malaysia.description, "Malaysia")
        XCTAssertEqual(CountryCode.maldives.description, "Maldives")
        XCTAssertEqual(CountryCode.mali.description, "Mali")
        XCTAssertEqual(CountryCode.malta.description, "Malta")
        XCTAssertEqual(CountryCode.marshallIslands.description, "Marshall Islands")
        XCTAssertEqual(CountryCode.martinique.description, "Martinique")
        XCTAssertEqual(CountryCode.mauritania.description, "Mauritania")
        XCTAssertEqual(CountryCode.mauritius.description, "Mauritius")
        XCTAssertEqual(CountryCode.mayotte.description, "Mayotte")
        XCTAssertEqual(CountryCode.mexico.description, "Mexico")
        XCTAssertEqual(CountryCode.micronesiaFederatedStatesOf.description, "Micronesia, Federated States Of")
        XCTAssertEqual(CountryCode.moldova.description, "Moldova")
        XCTAssertEqual(CountryCode.monaco.description, "Monaco")
        XCTAssertEqual(CountryCode.mongolia.description, "Mongolia")
        XCTAssertEqual(CountryCode.montenegro.description, "Montenegro")
        XCTAssertEqual(CountryCode.montserrat.description, "Montserrat")
        XCTAssertEqual(CountryCode.morocco.description, "Morocco")
        XCTAssertEqual(CountryCode.mozambique.description, "Mozambique")
        XCTAssertEqual(CountryCode.myanmar.description, "Myanmar")
        XCTAssertEqual(CountryCode.namibia.description, "Namibia")
        XCTAssertEqual(CountryCode.nauru.description, "Nauru")
        XCTAssertEqual(CountryCode.nepal.description, "Nepal")
        XCTAssertEqual(CountryCode.netherlands.description, "Netherlands")
        XCTAssertEqual(CountryCode.newCaledonia.description, "New Caledonia")
        XCTAssertEqual(CountryCode.newZealand.description, "New Zealand")
        XCTAssertEqual(CountryCode.nicaragua.description, "Nicaragua")
        XCTAssertEqual(CountryCode.niger.description, "Niger")
        XCTAssertEqual(CountryCode.nigeria.description, "Nigeria")
        XCTAssertEqual(CountryCode.niue.description, "Niue")
        XCTAssertEqual(CountryCode.norfolkIsland.description, "Norfolk Island")
        XCTAssertEqual(CountryCode.northernMarianaIslands.description, "Northern Mariana Islands")
        XCTAssertEqual(CountryCode.norway.description, "Norway")
        XCTAssertEqual(CountryCode.oman.description, "Oman")
        XCTAssertEqual(CountryCode.pakistan.description, "Pakistan")
        XCTAssertEqual(CountryCode.palau.description, "Palau")
        XCTAssertEqual(CountryCode.palestinianTerritoryOccupied.description, "Palestinian Territory, Occupied")
        XCTAssertEqual(CountryCode.panama.description, "Panama")
        XCTAssertEqual(CountryCode.papuaNewGuinea.description, "Papua New Guinea")
        XCTAssertEqual(CountryCode.paraguay.description, "Paraguay")
        XCTAssertEqual(CountryCode.peru.description, "Peru")
        XCTAssertEqual(CountryCode.philippines.description, "Philippines")
        XCTAssertEqual(CountryCode.pitcairn.description, "Pitcairn")
        XCTAssertEqual(CountryCode.poland.description, "Poland")
        XCTAssertEqual(CountryCode.portugal.description, "Portugal")
        XCTAssertEqual(CountryCode.puertoRico.description, "Puerto Rico")
        XCTAssertEqual(CountryCode.qata.description, "Qata")
        XCTAssertEqual(CountryCode.reunion.description, "Reunion")
        XCTAssertEqual(CountryCode.romania.description, "Romania")
        XCTAssertEqual(CountryCode.russianFederation.description, "Russian Federation")
        XCTAssertEqual(CountryCode.rwanda.description, "Rwanda")
        XCTAssertEqual(CountryCode.saintBartholemy.description, "Saint Bartholemy")
        XCTAssertEqual(CountryCode.saintHelena.description, "Saint Helena")
        XCTAssertEqual(CountryCode.saintKittsAndNevis.description, "Saint Kitts and Nevis")
        XCTAssertEqual(CountryCode.saintLucia.description, "Saint Lucia")
        XCTAssertEqual(CountryCode.saintMartin.description, "Saint Martin")
        XCTAssertEqual(CountryCode.saintPierreAndMiquelon.description, "Saint Pierre and Miquelon")
        XCTAssertEqual(CountryCode.saintVincentAndTheGrenadines.description, "Saint Vincent and The Grenadines")
        XCTAssertEqual(CountryCode.samoa.description, "Samoa")
        XCTAssertEqual(CountryCode.sanMarino.description, "San Marino")
        XCTAssertEqual(CountryCode.saoTomeAndPrincipe.description, "Sao Tome and Principe")
        XCTAssertEqual(CountryCode.saudiArabia.description, "Saudi Arabia")
        XCTAssertEqual(CountryCode.senegal.description, "Senegal")
        XCTAssertEqual(CountryCode.serbia.description, "Serbia")
        XCTAssertEqual(CountryCode.seychelles.description, "Seychelles")
        XCTAssertEqual(CountryCode.sierraLeone.description, "Sierra Leone")
        XCTAssertEqual(CountryCode.sintMaarten.description, "Sint Maarten")
        XCTAssertEqual(CountryCode.singapore.description, "Singapore")
        XCTAssertEqual(CountryCode.slovakia.description, "Slovakia")
        XCTAssertEqual(CountryCode.slovenia.description, "Slovenia")
        XCTAssertEqual(CountryCode.solomonIslands.description, "Solomon Islands")
        XCTAssertEqual(CountryCode.somalia.description, "Somalia")
        XCTAssertEqual(CountryCode.southAfrica.description, "South Africa")
        XCTAssertEqual(CountryCode.southGeorgiaAndTheSouthSandwichIslands.description, "South Georgia and The South Sandwich Islands")
        XCTAssertEqual(CountryCode.spain.description, "Spain")
        XCTAssertEqual(CountryCode.sriLanka.description, "Sri Lanka")
        XCTAssertEqual(CountryCode.sudan.description, "Sudan")
        XCTAssertEqual(CountryCode.suriname.description, "Suriname")
        XCTAssertEqual(CountryCode.svalbardAndJanMayen.description, "Svalbard and Jan Mayen")
        XCTAssertEqual(CountryCode.swaziland.description, "Swaziland")
        XCTAssertEqual(CountryCode.sweden.description, "Sweden")
        XCTAssertEqual(CountryCode.switzerland.description, "Switzerland")
        XCTAssertEqual(CountryCode.syrianArabRepublic.description, "Syrian Arab Republic")
        XCTAssertEqual(CountryCode.taiwan.description, "Taiwan")
        XCTAssertEqual(CountryCode.tajikistan.description, "Tajikistan")
        XCTAssertEqual(CountryCode.tanzaniaUnitedRepublicOf.description, "Tanzania, United Republic Of")
        XCTAssertEqual(CountryCode.thailand.description, "Thailand")
        XCTAssertEqual(CountryCode.timorLeste.description, "Timor-Leste")
        XCTAssertEqual(CountryCode.togo.description, "Togo")
        XCTAssertEqual(CountryCode.tokelau.description, "Tokelau")
        XCTAssertEqual(CountryCode.tonga.description, "Tonga")
        XCTAssertEqual(CountryCode.trinidadAndTobago.description, "Trinidad And Tobago")
        XCTAssertEqual(CountryCode.tunisia.description, "Tunisia")
        XCTAssertEqual(CountryCode.turkey.description, "Turkey")
        XCTAssertEqual(CountryCode.turkmenistan.description, "Turkmenistan")
        XCTAssertEqual(CountryCode.turksAndCaicosIslands.description, "Turks and Caicos Islands")
        XCTAssertEqual(CountryCode.tuvalu.description, "Tuvalu")
        XCTAssertEqual(CountryCode.uganda.description, "Uganda")
        XCTAssertEqual(CountryCode.ukraine.description, "Ukraine")
        XCTAssertEqual(CountryCode.unitedArabEmirates.description, "United Arab Emirates")
        XCTAssertEqual(CountryCode.unitedKingdom.description, "United Kingdom")
        XCTAssertEqual(CountryCode.unitedStates.description, "United States")
        XCTAssertEqual(CountryCode.unitedStatesMinorOutlyingIslands.description, "United States Minor Outlying Islands")
        XCTAssertEqual(CountryCode.uruguay.description, "Uruguay")
        XCTAssertEqual(CountryCode.uzbekistan.description, "Uzbekistan")
        XCTAssertEqual(CountryCode.vanuatu.description, "Vanuatu")
        XCTAssertEqual(CountryCode.venezuela.description, "Venezuela")
        XCTAssertEqual(CountryCode.vietNam.description, "Viet Nam")
        XCTAssertEqual(CountryCode.virginIslandsBritish.description, "Virgin Islands, British")
        XCTAssertEqual(CountryCode.virginIslandsUS.description, "Virgin Islands, U.S.")
        XCTAssertEqual(CountryCode.wallisAndFutuna.description, "Wallis and Futuna")
        XCTAssertEqual(CountryCode.westernSahara.description, "Western Sahara")
        XCTAssertEqual(CountryCode.yemen.description, "Yemen")
        XCTAssertEqual(CountryCode.zambia.description, "Zambia")
        XCTAssertEqual(CountryCode.zimbabwe.description, "Zimbabwe")
    }
    
    static var allTests : [(String, (CountryCodeSpec) -> () throws -> Void)] {
        return [
            ("testRawValues", testRawValues),
            ("testDescriptions", testDescriptions),
        ]
    }
}
